name: Dependabot auto-merge

on:
    pull_request:
        types: [opened, reopened, synchronize]

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    dependabot:
        runs-on: ubuntu-latest

        if: ${{ github.actor == 'dependabot[bot]' }}

        steps:
            - name: Dependabot metadata
              id: metadata
              uses: dependabot/fetch-metadata@v3
              with:
                  github-token: '${{ secrets.GITHUB_TOKEN }}'

            - name: Approve PR
              run: gh pr review --approve "$PR_URL"
              env:
                  PR_URL: ${{ github.event.pull_request.html_url }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Enable auto-merge for security updates
              if: ${{ steps.metadata.outputs.alert-state == 'OPEN' }}
              run: gh pr merge --auto --squash "$PR_URL"
              env:
                  PR_URL: ${{ github.event.pull_request.html_url }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Enable auto-merge for patch and minor updates
              if: ${{ steps.metadata.outputs.alert-state != 'OPEN' && contains(fromJSON('["version-update:semver-patch", "version-update:semver-minor"]'), steps.metadata.outputs.update-type) }}
              run: gh pr merge --auto --squash "$PR_URL"
              env:
                  PR_URL: ${{ github.event.pull_request.html_url }}
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
